sonar.organization=thomas7520
sonar.projectKey=Thomas7520_e4a-projet-billetterie
sonar.projectName=e4a-projet-billetterie

sonar.sources=client/src,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,server/seed-concerts.js

sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
